# 공통
spring.application.name=matmatgotgot
spring.config.import=optional:application-secret.properties

#server port
server.port=9999

##mysql settings
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/matgotdb?serverTimezone=UTC&characterEncoding=UTF-8}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
#
##mybatis settings
#mybatis.configuration.map-underscore-to-camel-case=true
#mybatis.mapper-locations=classpath:mapper/**/*.xml
#mybatis.type-aliases-package=com.twotwo.matmatgotgot.domain.*
#mybatis.configuration.jdbc-type-for-null=NULL
#mybatis.configuration.default-fetch-size=100
#mybatis.configuration.default-statement-timeout=30
#
##email settings
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${SPRING_MAIL_USERNAME:}
#spring.mail.password=${SPRING_MAIL_PASSWORD:}
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.auth=true
#
##jwt settings
#jwt.secret=${JWT_SECRET:}
#jwt.expiration=${JWT_EXPIRATION:86400000}
#
##file upload settings
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=50MB
#file.root=${FILE_ROOT:/tmp/uploads/web/matgot/}
#
## Google OAuth2 Client Settings
#spring.security.oauth2.client.registration.google.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:}
#spring.security.oauth2.client.registration.google.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET:}
#spring.security.oauth2.client.registration.google.redirect-uri=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI:}
#
## NAVER KEY - kgy
#naver.client.id.k=${NAVER_CLIENT_ID_K:}
#naver.client.secret.k=${NAVER_CLIENT_SECRET_K:}
#
## CLOVA OCR
#clova.ocr.secret-key=${CLOVA_OCR_SECRET_KEY:}
#clova.ocr.api-url=${CLOVA_OCR_API_URL:}
#
## NAVER API
#naver.client-id=${NAVER_CLIENT_ID:}
#naver.secret=${NAVER_SECRET:}
#
## IAM 사용자의 액세스 키
#cloud.aws.credentials.access-key=${CLOUD_AWS_CREDENTIALS_ACCESS_KEY:}
#cloud.aws.credentials.secret-key=${CLOUD_AWS_CREDENTIALS_SECRET_KEY:}
## S3 버킷이 위치한 리전 (서울 리전: ap-northeast-2)
#cloud.aws.region.static=${CLOUD_AWS_REGION_STATIC:ap-northeast-2}
## 업로드 대상 S3 버킷 이름
#cloud.aws.s3.bucket=${CLOUD_AWS_S3_BUCKET:}

#mysql settings
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

#mybatis settings
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.twotwo.matmatgotgot.domain.*
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.configuration.default-fetch-size=100
mybatis.configuration.default-statement-timeout=30

#email settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.auth=true

#jwt settings
jwt.secret=
jwt.expiration=

#file upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
file.root=

# Google OAuth2 Client Settings
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.redirect-uri=

# NAVER KEY - kgy
naver.client.id.k=
naver.client.secret.k=

# CLOVA OCR
clova.ocr.secret-key=
clova.ocr.api-url=

# NAVER API
naver.client-id=
naver.secret=

# IAM 사용자의 액세스 키
cloud.aws.credentials.access-key=
cloud.aws.credentials.secret-key=
# S3 버킷이 위치한 리전 (서울 리전: ap-northeast-2)
cloud.aws.region.static=
# 업로드 대상 S3 버킷 이름
cloud.aws.s3.bucket=